---

- name: create sub-site dir
  file:
    path: "/var/www/drupal/sites/{{ institutional_fqdn }}"
    state: directory
    owner: www-data

- name: create database
  mysql_db:
    name: "{{ drupal_mysql_database }}"

- name: create db user
  mysql_user: 
    name: "{{ drupal_mysql_user }}"
    password: "{{ drupal_mysql_password }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"
    state: present
    
- name: Install Drupal.
  command: '
    drush si standard -y
    --account-name=admin
    --account-pass=admin
    --db-url=mysql://{{ drupal_mysql_user }}:{{ drupal_mysql_password }}@localhost/{{ drupal_mysql_database }}
    --site-name="{{ drupal_site_name }}"
    -l "{{ institutional_fqdn }}" --sites-subdir="{{ institutional_fqdn }}"
    chdir={{ drupal_core_path }}
    creates={{ drupal_core_path }}/settings.php'

- name: give fedora access to the db
  lineinfile:
    dest:  "{{ fedora_home }}/fedora/server/config/filter-drupal.xml"
    line: |    
      <connection server="localhost" port="3306" dbname="{{ drupal_mysql_database  }}" user="{{ drupal_mysql_user }}" password="{{ drupal_mysql_password }}">
          <sql>
          <!--Different sql statement for each connection.  This is for drupal
          multisites that are setup using one database with table prefixes.
          We don\'t do this but some people might.-->
          SELECT DISTINCT u.uid AS userid, u.name AS Name, u.pass AS Pass,r.name AS Role FROM (users u LEFT JOIN users_roles ON u.uid=users_roles.uid) LEFT JOIN role r ON r.rid=users_roles.rid WHERE u.name=? AND u.pass=?;
          </sql>
      </connection>
    insertbefore: "</FilterDrupal_Connection>"

- name: restart tomcat7 to pick up the new drupal filter
  service:
    name: tomcat7
    state: restarted

- wait_for:
    port: 8080
    delay: 20


#- name: set theme
#  command: 'drush vset theme_default subtheme_lsu'
#  args:
#    chdir: "{{ drupal_core_path }}"

- name: set site name
  command: 'drush vset site_name {{ drupal_site_name  }}'
  args:
    chdir: "{{ drupal_core_path }}"

- name: update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1       {{ institutional_fqdn }}"
    insertafter: '127\.0\.0\.1\tlocalhost'
